name: "Build ISO"

on:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        arch:
          - x86_64
          # - aarch64

    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false
        
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: DeterminateSystems/flake-checker-action@main

    - name: Print flake metadata
      run: nix flake metadata --accept-flake-config
    - name: Build x86_64 ISO
      if: ${{ matrix.arch == 'x86_64' }}
      run: nix build .#iso --accept-flake-config
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        path: |
          result/**/*.iso
