name: "Build ISO"

on:
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        arch:
          - x86_64
          # - aarch64
        nixPath:
          - nixpkgs=channel:nixos-unstable
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install nix
      uses: cachix/install-nix-action@v23
      with:
        nix_path: "${{ matrix.nixPath }}"
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Show nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - name: Setup Github Caches
      uses: DeterminateSystems/magic-nix-cache-action@v2
    - name: Build x86_64 ISO
      if: ${{ matrix.arch == 'x86_64' }}
      run: nix build .#iso
